version: 2.1

jobs:
  integration-test:
    parameters:
      php-version:
        type: string
      symfony-version:
        type: string
    docker:
      # node-browsers come with java pre-installed
      - image: circleci/php:<< parameters.php-version >>-node-browsers
    working_directory: ~/openzipkin
    steps:
      - checkout
      - run: sudo apt install rsync
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run: curl -sSL https://zipkin.io/quickstart.sh | bash -s
      - run:
          background: true
          command: java -jar zipkin.jar
      # block until zipkin is available
      - run: wget --retry-connrefused -T 60 -O /dev/null http://127.0.0.1:9411/health
      # start both processes in the background, but don't use composer as it dies
      - run:
          command: cd ./tests/Integration && make SYMFONY_VERSION=<< parameters.symfony-version >> LIBRARY_BRANCH=${CIRCLE_BRANCH} COMPOSER_RUNNER="php -d memory_limit=-1 /home/circleci/openzipkin/composer.phar" build
      - run:
          background: true
          command: php ./tests/Integration/test-app/bin/console server:run 8002
      - run: wget -v --retry-connrefused -T 5 -O /dev/null 127.0.0.1:8002/_health
      - run: |
          # wait just in case
          sleep 1
          # makes sure we get one trace
          test $(curl -s 127.0.0.1:9411/api/v2/traces | jq '.[0] | length') -eq 1
          # makes sure the trace does not contain errors
          test $(curl -s 127.0.0.1:9411/api/v2/traces | jq -c '.[0][0].tags.error') = "null"
          exit $?

workflows:
  all-tests:
    jobs:
      - integration-test:
          matrix:
            parameters:
              php-version: ["7.1", "7.2", "7.3"]
              symfony-version: ["3.4", "4.4", "5.1"]
            exclude:
              - php-version: "7.1"
                symfony-version: "5.1"
