services:
  zipkin.default_tracing:
    class: Zipkin\DefaultTracing
    public: true
    factory: [ZipkinBundle\TracingFactory, build]
    arguments:
      - "@service_container"

  zipkin.sampler.route:
    class: ZipkinBundle\Samplers\RouteSampler
    public: true
    arguments:
      - "@request_stack"
      - "%zipkin.sampler.route.included_routes%"
      - "%zipkin.sampler.route.excluded_routes%"

  zipkin.sampler.path:
    class: ZipkinBundle\Samplers\PathSampler
    public: true
    arguments:
      - "@request_stack"
      - "%zipkin.sampler.path.included_paths%"
      - "%zipkin.sampler.path.excluded_paths%"

  zipkin.messenger.middleware:
    class: ZipkinBundle\Components\Messenger\ZipkinMiddleware
    public: true
    arguments:
      - "@zipkin.messenger.send_handler"
      - "@zipkin.messenger.receive_handler"

  zipkin.messenger.send_handler:
    class: ZipkinBundle\Components\Messenger\ZipkinSendHandler
    arguments:
      - "@zipkin.default_tracing"

  zipkin.messenger.receive_handler:
    class: ZipkinBundle\Components\Messenger\ZipkinReceiveHandler
    arguments:
      - "@zipkin.default_tracing"